# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.ssh.forward_x11 = true

  config.vm.define "docker" do |docker|
    docker.vm.box = "ubuntu/trusty64"
    docker.vm.synced_folder "c:/Tools/vagrant/data", "/srv/data"
    docker.vm.hostname = "docker"
    docker.vm.network :private_network, ip: "10.11.12.4"
    docker.vm.network :forwarded_port, guest: 22, host: 2224, id: "ssh"
    #docker.vm.network "public_network"

    docker.vm.provider "virtualbox" do |v|
        v.memory = 8192
        v.name = "docker"
        v.cpus = 2
    end

  end

end
