# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.ssh.forward_x11 = true

  config.vm.define "appServer01" do |appServer01|
    appServer01.vm.box = "ubuntu/trusty32"
    appServer01.vm.synced_folder "c:/Tools/data", "/srv/data"
    appServer01.vm.hostname = "appServer01"
    appServer01.vm.network :private_network, ip: "10.11.12.5"
    appServer01.vm.network "public_network"
    appServer01.vm.network :forwarded_port, guest: 22, host: 2225, id: "ssh"

    appServer01.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.name = "appServer01"
        v.cpus = 2
    end

  end

end
