# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.ssh.forward_x11 = true

  config.vm.define "hadoop" do |hadoop|
    hadoop.vm.box = "ubuntu/trusty32"
    hadoop.vm.synced_folder "c:/Tools/vagrant/data", "/srv/data"
    hadoop.vm.hostname = "hadoop"
    hadoop.vm.network :private_network, ip: "10.11.12.6"
    hadoop.vm.network "public_network"
    hadoop.vm.network :forwarded_port, guest: 22, host: 2226, id: "ssh"

    hadoop.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.name = "hadoop"
        v.cpus = 2
    end

  end

end
